name: "Common Publish Action"
description: "A common action for publishing a package and pushing Docker images"
inputs:
  script:
    description: |
            package.jsonアップデートのために実行するスクリプトのパス。
            引数がある場合も半角スペースを入れれば認識する。
    required: true
  push_branches:
    description: push対象のブランチ名をコンマ区切りで指定する
    required: true
  create_tag:
    description: |
            タグを作成するかどうかを指定する。
            trueの場合はタグを作成する。
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: finish
      shell: bash
      run: echo 'finish ${{ inputs.script }} ${{ inputs.push_branches }} ${{ inputs.create_tag }}'
