name: common publish workflow

on:
  workflow_call:
    inputs:
      script:
        type: string
        description: |
            package.jsonアップデートのために実行するスクリプトのパス。
            引数がある場合も半角スペースを入れれば認識する。
        required: true
      push_branches:
        type: string
        description: push対象のブランチ名をコンマ区切りで指定する
        required: true
      create_tag:
        type: boolean
        description: |
            タグを作成するかどうかを指定する。
            trueの場合はタグを作成する。
        required: false
        default: false

permissions:
  contents: write
  packages: write
  # workaround for https://github.com/cli/cli/issues/6274
  repository-projects: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo "${{ github.event.inputs.script }} ${{ github.event.inputs.push_branches }} ${{ github.event.inputs.create_tag }}"
