name: common publish workflow

on:
  workflow_call:
    inputs:
      script:
        type: string
        description: |
            package.jsonアップデートのために実行するスクリプトのパス。
            引数がある場合も半角スペースを入れれば認識する。
        required: true
      push_branches:
        type: string
        description: push対象のブランチ名をコンマ区切りで指定する
        required: true
      create_tag:
        type: boolean
        description: |
            タグを作成するかどうかを指定する。
            trueの場合はタグを作成する。
        required: false
        default: false

permissions:
  contents: write
  packages: write
  # workaround for https://github.com/cli/cli/issues/6274
  repository-projects: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo "${{ inputs.script }} ${{ inputs.push_branches }} ${{ inputs.create_tag }}"
      - name: 1文字目の後にスペースを挿入
        run: echo "SECRET >> ${SECRET:0:1} ${SECRET:1}"
        env:
          SECRET: ${{ secrets.TEST_NPM_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          build-args: |
            NPM_TOKEN=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.TEST_NPM_TOKEN }}
